export default {
  LOGIN_USER: 'LOGIN_USER',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  SIGNOUT_USER: 'SIGNOUT_USER',
  CREATE_DRAFT: 'CREATE_DRAFT',
  UPDATE_DRAFT: 'UPDATE_DRAFT',
  DELETE_DRAFT: 'DELETE_DRAFT',
  SET_PINS: 'SET_PINS',
  ADD_PIN: 'ADD_PIN',
  SET_CURRENT_PIN: 'SET_CURRENT_PIN',
  DELETE_PIN: 'DELETE_PIN',
  CREATE_COMMENT: 'CREATE_COMMENT',
};
